name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3

  # API Handling
  http: 1.3.0

  # UI & Utility Packages
  cached_network_image: ^3.2.3  # Efficient image loading
  equatable: ^2.0.5  # Helps in comparing objects in BLoC

  # Icons & Styling
  google_fonts: ^5.1.0  # Custom fonts
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true